### PR TITLE
[New Mix Type] Experience / Other Updates

### PR DESCRIPTION
**Pull request by PencilMario**
1. New mix type: experience (exp)

    > Note:
    > The extension [SteamWorks](https://github.com/KyleSanderson/SteamWorks) is required.

    This mix type rates players based on their actual game time and game statistics displayed in the player achievement interface. Then, teams are formed based on the rating data of all players. There are three team formation algorithms:

    - **Average** - ensures that the average score difference between the two teams is as small as possible (when `sm_mix_exp_type = 0`, the score difference between the two teams should be less than 2500).
    - **Balance** - the strength composition of the two teams is relatively close (the first, third, sixth, and eighth players form one team, and the remaining players form the other team).
    - **Slot** - first assign one player who commonly uses a shotgun to each team, and then allocate the remaining players using the *Average* algorithm (the two shotgun players must be in the top four rankings).

    You can also use cvar `sm_mix_exp_type` to force a specific team formation method. 0=Auto 1=Average 2=Balance 3=Slot.
    ~~I encountered many problems, and although the code is bad, at least it works XD~~

2. Add Chi translation.

3. ~~Add CallEndMix() function to mt_random.~~

### CODE REVIEW

**Comment by PencilMario** [comment]
fixed #3

**Comment by TouchMe-Inc** [comment]
Thank you for your work! I need some time to deal with the bugs you noted (it seems that in version 2.3 I fixed them)

**Comment by TouchMe-Inc** [comment]
I opened a new Dev branch, which after some testing will be merged into Main. Some natives will be updated here, which will interfere with your mix.
Major changes  `AddMixType -> AddMix`, `CallEndMix -> Call_FinishMix`, `CallCancelMix -> Call_AbortMix` (DEV)

**Comment by TouchMe-Inc** [comment]
You can also change ripext to [SteamWorks](https://github.com/hexa-core-eu/SteamWorks)
```pawn
SteamWorks_RequestStats(iClient, 550/*APP L4D2*/);
SteamWorks_GetStatCell(iClient, "Stat.TotalPlayTime.Total", iPlayer.gametime);
```
From the pros: 
* No need for API_KEY
* No need to parse answers

I want to add your mix to master branch after merge from dev.

### In any case, good work has been done!

**Comment by TouchMe-Inc** [comment]
Dev merged into Main. The wiki page has been updated. The mix_team.inc file received more detailed comments.
I remind you that natives have been changed:
```
AddMixType -> AddMix
CallEndMix -> Call_FinishMix
CallCancelMix -> Call_AbortMix
```

**Comment by PencilMario** [comment]
Although I haven't tested it yet, there shouldn't be any problem :)

**Comment by TouchMe-Inc** [comment]
I tried to make a simpler version of the plugin, but did not test it
Only the Balance method is implemented (for any number of players from 4 to 8+)
[code](https://gist.github.com/TouchMe-Inc/24395a516edf986f1fddcf0e75e3ab19)

**Comment by PencilMario** [comment]
Unfortunately, the code cannot be compiled.
```
SourcePawn Compiler 1.10.0.6502
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(73) : warning 219: local variable "iClient" shadows a variable at a preceding level
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(77) : warning 219: local variable "iClient" shadows a variable at a preceding level
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(88) : warning 219: local variable "tPlayerStats" shadows a variable at a preceding level
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(90) : warning 219: local variable "iClient" shadows a variable at a preceding level
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(96) : error 017: undefined symbol "GetPlayerStats"
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(96) : error 047: array sizes do not match, or destination array is too small
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(146) : warning 219: local variable "iClient" shadows a variable at a preceding level
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(153) : error 001: expected token: ";", but found "("
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(157) : error 147: new-style declarations are required
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(166) : error 010: invalid function or declaration
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(169) : warning 219: local variable "tPlayerStats" shadows a variable at a preceding level
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(223) : warning 219: local variable "iClient" shadows a variable at a preceding level
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(157) : warning 203: symbol is never used: "__unknown__"
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(157) : warning 203: symbol is never used: "iClient"
e:\GithubKu\l4d2_mix_team\addons\sourcemod\scripting\mt.sp(155) : warning 203: symbol is never used: "tPlayerStats"

5 Errors.
```

**Comment by TouchMe-Inc** [comment]
You may not have copied everything.
copy raw https://gist.githubusercontent.com/TouchMe-Inc/24395a516edf986f1fddcf0e75e3ab19/raw/226d9ece6e5ebbe9a387726253230bb17140720e/mt_exp

**Comment by PencilMario** [comment]
The outcome is the same. Could this be due to the version of SourceMod?

**Comment by TouchMe-Inc** [comment]
My SM v1.11.0.6911
Mb will fix `any[] GetPlayerStats(int iClient)`

**Comment by PencilMario** [comment]
I switched the version to your version, and now it compiles.

**Comment by PencilMario** [comment]
After a period of testing, no one has reported any bugs to me, so it seems like there should be no issues.

**Pull request merged**
